DROP DATABASE testDB;

CREATE DATABASE testDB;

USE testDB;

CREATE TABLE users (
  id    INT PRIMARY KEY AUTO_INCREMENT,
  login VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE groups (
  id   INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE users_groups (
  user_id  INTEGER REFERENCES users (id),
  group_id INTEGER REFERENCES groups (id)
);

INSERT INTO users VALUE (DEFAULT, "ivanov");
INSERT INTO groups VALUE (DEFAULT, "teamA");

SELECT * FROM users;
SELECT * FROM groups;

